[build]
  command = "npm start"  # O el comando que usas para construir tu aplicación
  publish = "public"  # Ruta de los archivos que Netlify debe desplegar

[context.production.environment]
  NODE_VERSION = "21"  # Versión específica de Node.js

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Content-Security-Policy = '''
        default-src 'self';
        script-src 'self' https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/ https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ https://unpkg.com/split-type@0.3.4/umd/;
      '''

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200